from manim import *
class pro01(Scene):
    def construct(self):
        title=Text("Proposition 1",font_size=40).to_edge(UL)
        p1=np.array([-1,0,0])
        p2=np.array([1,0,0])
        p3=np.array([0,np.sqrt(3),0])
        a=Dot(p1)
        b=Dot(p2)
        line=Line(p1,p2,color=RED)
        a_text=Text("A",font_size=30).next_to(a,LEFT)
        b_text=Text("B",font_size=30).next_to(b,RIGHT)
        self.add(title,line,a,b,a_text,b_text)
        self.wait(2)

        cir1=Circle(radius=2,color=BLUE_C).move_to(LEFT)
        cir2=Circle(radius=2,color=BLUE_C).move_to(RIGHT).rotate(PI)
        tri=Polygon(p2,p3,p1,fill_color=RED_C,fill_opacity=0.5,
                    stroke_color=RED,stroke_width=6)    
        self.play(Create(cir1),run_time=2)
        self.play(Create(cir2),run_time=2)
        self.play(DrawBorderThenFill(tri),run_time=2)
        self.wait(3)

class pro02(Scene):
    def dis(self,pa,pb):
        d=np.sqrt((pa[0]-pb[0])**2+(pa[1]-pb[1])**2)
        return d
    def construct(self):
        title=Text("Proposition 2",font_size=40).to_edge(UL)
        p1=np.array([-0.5,1,0])
        p2=np.array([1.5,1,0])
        p3=np.array([0.2,-0.2,0])
        a=Dot(p1)
        b=Dot(p2)
        c=Dot(p3)
        line=Line(p1,p2,color=RED,)
        a_text=Text("A",font_size=30).next_to(a,LEFT)
        b_text=Text("B",font_size=30).next_to(b,RIGHT)
        c_text=Text("C",font_size=30).next_to(c,DOWN)
        self.add(title,line,a,b,c,a_text,b_text,c_text)

        cir1=Circle(radius=self.dis(p1,p3),color=BLUE_C).move_to(p1).rotate(-PI/3)
        cir2=Circle(radius=self.dis(p1,p3),color=BLUE_C).move_to(p3).rotate(2*PI/3)
        p4=a.copy().rotate(PI/3,about_point=p3).get_center()
        line1=Line(p4,(p1-p4)*3+p4)
        line2=Line(p4,(p3-p4)*3+p4)
        cir3=Circle(radius=self.dis(p1,p2),color=BLUE_C).move_to(p1)
        p5=p1+(p1-p4)*self.dis(p1,p2)/self.dis(p1,p4)
        d=Dot(p5)
        d_text=Text("D",font_size=30).next_to(d,RIGHT)
        cir4=Circle(radius=self.dis(p4,p5),color=BLUE_C).move_to(p4).rotate(PI/3)
        p6=p4+(p3-p4)*self.dis(p4,p5)/self.dis(p3,p4)
        e=Dot(p6)
        e_text=Text("E",font_size=30).next_to(e,DR)
        line3=Line(p3,p6).set_color(RED)
        self.play(Create(cir1),run_time=2)
        self.play(Create(cir2),run_time=2)
        self.wait()
        self.play(Create(line1),run_time=2)
        self.play(Create(line2),run_time=2)
        self.play(FadeOut(cir1,cir2),run_time=2)
        self.play(Create(cir3),run_time=2)
        self.add(d,d_text)
        self.wait()
        self.play(Create(cir4),run_time=2)
        self.add(e,e_text)
        self.wait()
        self.add(Dot(p3).set_color(RED))
        self.play(Create(line3),run_time=2)
        e.set_color(RED)
        self.wait(5)
                
class pro03(Scene):
    def dis(self,pa,pb):
        return np.sqrt((pa[0]-pb[0])**2+(pa[1]-pb[1])**2)
    def ang(self,p,o):
        return np.arctan((p[1]-o[1])/(p[0]-o[0]))     
    def construct(self):
        title=Text("Proposition 3",font_size=40).to_edge(UL)
        p1=np.array([-0.5,1,0])
        p2=np.array([1.5,1,0])
        p3=np.array([-0.3,-0.5,0])
        p4=np.array([4.5,-0.5,0])
        a=Dot(p1)
        b=Dot(p2)
        c=Dot(p3)
        d=Dot(p4)
        l1=Line(p1,p2,color=RED)
        l2=Line(p3,p4,color=BLUE)
        a_text=Text("A",font_size=30).next_to(a,LEFT)
        b_text=Text("B",font_size=30).next_to(b,RIGHT)
        c_text=Text("C",font_size=30).next_to(c,DOWN)
        d_text=Text("D",font_size=30).next_to(d,DOWN)
        self.add(title,l1,l2,a,b,c,d,a_text,b_text,c_text,d_text)

        cir1=Circle(radius=self.dis(p1,p3),color=GREEN_D).move_to(p1).rotate(self.ang(p3,p1))
        cir2=Circle(radius=self.dis(p1,p3),color=GREEN_D).move_to(p3).rotate(-self.ang(p1,p3))
        p=a.copy().rotate(PI/3,about_point=p3).get_center()
        line1=Line(p,(p1-p)*3+p)
        line2=Line(p,(p3-p)*3+p)
        self.play(Create(cir1),run_time=1.5)
        self.play(Create(cir2),run_time=1.5)
        self.play(Create(line1),run_time=2)
        self.play(Create(line2),run_time=2)
        self.play(FadeOut(cir1,cir2),run_time=1.5)
        cir3=Circle(radius=self.dis(p1,p2),color=BLUE_C).move_to(p1)
        pp=p1+(p1-p)*self.dis(p1,p2)/self.dis(p1,p)
        pp_dot=Dot(pp)
        cir4=Circle(radius=self.dis(p,pp),color=BLUE_C).move_to(p).rotate(self.ang(pp,p))
        p5=p+(p3-p)*self.dis(p,pp)/self.dis(p3,p)
        e=Dot(p5)
        e_text=Text("E",font_size=30).next_to(e,RIGHT)
        line3=Line(p3,p5).set_color(RED)
        self.play(Create(cir3),run_time=2)
        self.add(pp_dot)
        self.play(Create(cir4),run_time=2)
        self.add(e,e_text)
        self.add(Dot(p3).set_color(RED))
        self.play(Create(line3),run_time=2)
        e.set_color(RED)

        cir5=Circle(radius=self.dis(p3,p5),color=RED_D).move_to(p3).rotate(self.ang(p5,p3))
        p6=p3+(p2-p1)
        f=Dot(p6)
        f_text=Text("F",font_size=30).next_to(f,RIGHT)
        line4=Line(p3,p6).set_color(RED)
        self.play(Create(cir5),run_time=2)
        self.add(f,f_text)
        self.play(Create(line4),run_time=2)
        f.set_fill(RED)
        self.play(FadeOut(line3))
        e.set_color(WHITE)
        self.wait(5)